# Site settings
title: Buonzz Systems
email: darwin@buonzz.com
description: High Quality Open Source Applications.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.buonzz.com" # the base hostname & protocol for your site
twitter_username: buonzz
github_username:  buonzz-systems

# Build settings
markdown: kramdown
